// This file is auto-generated by @hey-api/openapi-ts

export const BacktestComparisonSchema = {
    properties: {
        comparison_id: {
            type: 'string',
            title: 'Comparison Id',
            description: 'Comparison ID'
        },
        backtests: {
            items: {
                '$ref': '#/components/schemas/BacktestComparisonItem'
            },
            type: 'array',
            title: 'Backtests',
            description: 'Compared backtests'
        },
        summary: {
            additionalProperties: true,
            type: 'object',
            title: 'Summary',
            description: 'Comparison summary'
        },
        created_at: {
            type: 'string',
            title: 'Created At',
            description: 'Comparison timestamp'
        }
    },
    type: 'object',
    required: ['comparison_id', 'backtests', 'summary', 'created_at'],
    title: 'BacktestComparison',
    description: 'Backtest comparison response model'
} as const;

export const BacktestComparisonItemSchema = {
    properties: {
        backtest_id: {
            type: 'string',
            title: 'Backtest Id',
            description: 'Backtest ID'
        },
        strategy_name: {
            type: 'string',
            title: 'Strategy Name',
            description: 'Strategy name'
        },
        symbol: {
            type: 'string',
            title: 'Symbol',
            description: 'Trading symbol'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date'
        },
        initial_capital: {
            type: 'number',
            title: 'Initial Capital',
            description: 'Initial capital'
        },
        final_value: {
            type: 'number',
            title: 'Final Value',
            description: 'Final portfolio value'
        },
        total_return: {
            type: 'number',
            title: 'Total Return',
            description: 'Total return'
        },
        total_return_pct: {
            type: 'number',
            title: 'Total Return Pct',
            description: 'Total return percentage'
        },
        sharpe_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharpe Ratio',
            description: 'Sharpe ratio'
        },
        max_drawdown: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Drawdown',
            description: 'Maximum drawdown'
        },
        total_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Trades',
            description: 'Total number of trades'
        },
        winning_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Winning Trades',
            description: 'Number of winning trades'
        },
        losing_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Losing Trades',
            description: 'Number of losing trades'
        },
        win_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Win Rate',
            description: 'Win rate'
        },
        avg_win: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Win',
            description: 'Average winning trade'
        },
        avg_loss: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Loss',
            description: 'Average losing trade'
        },
        avg_annual_return: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Annual Return',
            description: 'Average annual return'
        },
        vwr: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vwr',
            description: 'Variability-weighted return'
        },
        calmar_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Calmar Ratio',
            description: 'Calmar ratio'
        },
        sqn: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sqn',
            description: 'System quality number'
        },
        created_at: {
            type: 'string',
            title: 'Created At',
            description: 'Creation timestamp'
        }
    },
    type: 'object',
    required: ['backtest_id', 'strategy_name', 'symbol', 'start_date', 'end_date', 'initial_capital', 'final_value', 'total_return', 'total_return_pct', 'created_at'],
    title: 'BacktestComparisonItem',
    description: 'Backtest comparison item model'
} as const;

export const BacktestHistoryItemSchema = {
    properties: {
        backtest_id: {
            type: 'string',
            title: 'Backtest Id'
        },
        strategy_name: {
            type: 'string',
            title: 'Strategy Name'
        },
        symbol: {
            type: 'string',
            title: 'Symbol'
        },
        start_date: {
            type: 'string',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            title: 'End Date'
        },
        initial_capital: {
            type: 'number',
            title: 'Initial Capital'
        },
        final_value: {
            type: 'number',
            title: 'Final Value'
        },
        total_return: {
            type: 'number',
            title: 'Total Return'
        },
        sharpe_ratio: {
            type: 'number',
            title: 'Sharpe Ratio'
        },
        max_drawdown: {
            type: 'number',
            title: 'Max Drawdown'
        },
        total_trades: {
            type: 'integer',
            title: 'Total Trades'
        },
        win_rate: {
            type: 'number',
            title: 'Win Rate'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['backtest_id', 'strategy_name', 'symbol', 'start_date', 'end_date', 'initial_capital', 'final_value', 'total_return', 'sharpe_ratio', 'max_drawdown', 'total_trades', 'win_rate', 'created_at'],
    title: 'BacktestHistoryItem',
    description: 'Backtest history item model'
} as const;

export const BacktestHistoryListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BacktestHistoryItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: ['data', 'count', 'page', 'size', 'total_pages'],
    title: 'BacktestHistoryList',
    description: 'List of backtest history'
} as const;

export const BacktestRequestSchema = {
    properties: {
        symbol: {
            type: 'string',
            title: 'Symbol',
            description: 'Stock symbol (e.g., 000001.SZ)'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date (YYYY-MM-DD)'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date (YYYY-MM-DD)'
        },
        initial_capital: {
            type: 'number',
            title: 'Initial Capital',
            description: 'Initial capital',
            default: 1000000
        },
        commission: {
            type: 'number',
            title: 'Commission',
            description: 'Commission rate',
            default: 0.0003
        },
        commtype: {
            type: 'string',
            title: 'Commtype',
            description: 'Commission type: PERC or FIXED',
            default: 'PERC'
        },
        commmin: {
            type: 'number',
            title: 'Commmin',
            description: 'Minimum commission',
            default: 5
        },
        stocklike: {
            type: 'boolean',
            title: 'Stocklike',
            description: 'Stock-like instrument',
            default: true
        },
        leverage: {
            type: 'number',
            title: 'Leverage',
            description: 'Leverage ratio',
            default: 1
        },
        margin: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Margin',
            description: 'Margin requirement'
        },
        mode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mode',
            description: 'Trading mode',
            default: 'BACKTEST'
        }
    },
    type: 'object',
    required: ['symbol', 'start_date', 'end_date'],
    title: 'BacktestRequest',
    description: 'Backtest request model'
} as const;

export const BacktestResponseSchema = {
    properties: {
        backtest_id: {
            type: 'string',
            title: 'Backtest Id'
        },
        strategy_name: {
            type: 'string',
            title: 'Strategy Name'
        },
        symbol: {
            type: 'string',
            title: 'Symbol'
        },
        start_date: {
            type: 'string',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            title: 'End Date'
        },
        initial_capital: {
            type: 'number',
            title: 'Initial Capital'
        },
        performance: {
            '$ref': '#/components/schemas/PerformanceMetrics'
        },
        chart_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chart Path'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['backtest_id', 'strategy_name', 'symbol', 'start_date', 'end_date', 'initial_capital', 'performance', 'status'],
    title: 'BacktestResponse',
    description: 'Backtest response model'
} as const;

export const BacktestSortBySchema = {
    type: 'string',
    enum: ['created_at', 'start_date', 'end_date', 'total_return', 'sharpe_ratio', 'max_drawdown', 'total_trades'],
    title: 'BacktestSortBy',
    description: 'Backtest sorting options'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DataResponseSchema = {
    properties: {
        data: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        columns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Columns'
        }
    },
    type: 'object',
    required: ['data', 'count', 'columns'],
    title: 'DataResponse',
    description: 'Data response model'
} as const;

export const FactorCalculateRequestSchema = {
    properties: {
        factor_name: {
            type: 'string',
            title: 'Factor Name',
            description: 'Name of the factor to calculate'
        },
        data_type: {
            type: 'string',
            title: 'Data Type',
            description: 'Type of data: daily, minute, financial, macro, industry, concept'
        },
        symbol: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Symbol',
            description: 'Symbol for stock/fundamental data'
        },
        indicator: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Indicator',
            description: 'Indicator for macro data'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date in YYYY-MM-DD format'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date in YYYY-MM-DD format'
        },
        parameters: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parameters',
            description: 'Additional parameters for factor calculation'
        }
    },
    type: 'object',
    required: ['factor_name', 'data_type', 'start_date', 'end_date'],
    title: 'FactorCalculateRequest',
    description: 'Factor calculation request model'
} as const;

export const FactorCalculationResponseSchema = {
    properties: {
        factor_name: {
            type: 'string',
            title: 'Factor Name',
            description: 'Factor name'
        },
        symbol: {
            type: 'string',
            title: 'Symbol',
            description: 'Symbol'
        },
        calculation_time: {
            type: 'string',
            title: 'Calculation Time',
            description: 'Calculation timestamp'
        },
        data_points: {
            type: 'integer',
            title: 'Data Points',
            description: 'Number of data points calculated'
        },
        result_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Result Data',
            description: 'Calculation results'
        }
    },
    type: 'object',
    required: ['factor_name', 'symbol', 'calculation_time', 'data_points', 'result_data'],
    title: 'FactorCalculationResponse',
    description: 'Factor calculation response model'
} as const;

export const FactorInfoSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Factor name'
        },
        factor_type: {
            type: 'string',
            title: 'Factor Type',
            description: 'Factor type'
        },
        factor_class: {
            type: 'string',
            title: 'Factor Class',
            description: 'Factor class name'
        },
        description: {
            type: 'string',
            title: 'Description',
            description: 'Factor description'
        },
        parameters: {
            additionalProperties: true,
            type: 'object',
            title: 'Parameters',
            description: 'Factor parameters'
        },
        required_fields: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Fields',
            description: 'Required data fields'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Factor status'
        }
    },
    type: 'object',
    required: ['name', 'factor_type', 'factor_class', 'description', 'parameters', 'required_fields', 'status'],
    title: 'FactorInfo',
    description: 'Factor information response model'
} as const;

export const FactorRegisterRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Factor name'
        },
        factor_class: {
            type: 'string',
            title: 'Factor Class',
            description: 'Factor class name (e.g., MovingAverageFactor)'
        },
        description: {
            type: 'string',
            title: 'Description',
            description: 'Factor description'
        },
        parameters: {
            additionalProperties: true,
            type: 'object',
            title: 'Parameters',
            description: 'Factor parameters'
        }
    },
    type: 'object',
    required: ['name', 'factor_class', 'description', 'parameters'],
    title: 'FactorRegisterRequest',
    description: 'Factor registration request model'
} as const;

export const FactorStatusResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Factor name'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Current status'
        },
        last_calculation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Calculation',
            description: 'Last calculation time'
        },
        error_count: {
            type: 'integer',
            title: 'Error Count',
            description: 'Number of errors'
        },
        is_available: {
            type: 'boolean',
            title: 'Is Available',
            description: 'Whether factor is available'
        }
    },
    type: 'object',
    required: ['name', 'status', 'error_count', 'is_available'],
    title: 'FactorStatusResponse',
    description: 'Factor status response model'
} as const;

export const GlobalBacktestItemSchema = {
    properties: {
        backtest_id: {
            type: 'string',
            title: 'Backtest Id',
            description: 'Backtest ID'
        },
        strategy_name: {
            type: 'string',
            title: 'Strategy Name',
            description: 'Strategy name'
        },
        symbol: {
            type: 'string',
            title: 'Symbol',
            description: 'Trading symbol'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date'
        },
        initial_capital: {
            type: 'number',
            title: 'Initial Capital',
            description: 'Initial capital'
        },
        final_value: {
            type: 'number',
            title: 'Final Value',
            description: 'Final portfolio value'
        },
        total_return: {
            type: 'number',
            title: 'Total Return',
            description: 'Total return'
        },
        total_return_pct: {
            type: 'number',
            title: 'Total Return Pct',
            description: 'Total return percentage'
        },
        sharpe_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharpe Ratio',
            description: 'Sharpe ratio'
        },
        max_drawdown: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Drawdown',
            description: 'Maximum drawdown'
        },
        total_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Trades',
            description: 'Total number of trades'
        },
        winning_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Winning Trades',
            description: 'Number of winning trades'
        },
        losing_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Losing Trades',
            description: 'Number of losing trades'
        },
        win_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Win Rate',
            description: 'Win rate'
        },
        avg_win: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Win',
            description: 'Average winning trade'
        },
        avg_loss: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Loss',
            description: 'Average losing trade'
        },
        avg_annual_return: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Annual Return',
            description: 'Average annual return'
        },
        vwr: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vwr',
            description: 'Variability-weighted return'
        },
        calmar_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Calmar Ratio',
            description: 'Calmar ratio'
        },
        sqn: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sqn',
            description: 'System quality number'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Backtest status'
        },
        created_at: {
            type: 'string',
            title: 'Created At',
            description: 'Creation timestamp'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By',
            description: 'Creator email'
        }
    },
    type: 'object',
    required: ['backtest_id', 'strategy_name', 'symbol', 'start_date', 'end_date', 'initial_capital', 'final_value', 'total_return', 'total_return_pct', 'status', 'created_at'],
    title: 'GlobalBacktestItem',
    description: 'Global backtest item model'
} as const;

export const GlobalBacktestListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GlobalBacktestItem'
            },
            type: 'array',
            title: 'Data',
            description: 'List of backtests'
        },
        count: {
            type: 'integer',
            title: 'Count',
            description: 'Total number of backtests'
        },
        page: {
            type: 'integer',
            title: 'Page',
            description: 'Current page number'
        },
        size: {
            type: 'integer',
            title: 'Size',
            description: 'Page size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages',
            description: 'Total number of pages'
        }
    },
    type: 'object',
    required: ['data', 'count', 'page', 'size', 'total_pages'],
    title: 'GlobalBacktestList',
    description: 'Global backtest list response model'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IndustryConceptDataRequestSchema = {
    properties: {
        data_type: {
            type: 'string',
            title: 'Data Type',
            description: 'Data type: industry, concept'
        },
        use_cache: {
            type: 'boolean',
            title: 'Use Cache',
            description: 'Use cached data if available',
            default: true
        }
    },
    type: 'object',
    required: ['data_type'],
    title: 'IndustryConceptDataRequest',
    description: 'Industry/Concept data request model'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MacroDataRequestSchema = {
    properties: {
        data_type: {
            type: 'string',
            title: 'Data Type',
            description: 'Data type: macro',
            default: 'macro'
        },
        indicator: {
            type: 'string',
            title: 'Indicator',
            description: 'Macro indicator: gdp, cpi, ppi, m2, interest_rate'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date (e.g., 2022-01-01)'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date (e.g., 2022-12-31)'
        },
        use_cache: {
            type: 'boolean',
            title: 'Use Cache',
            description: 'Use cached data if available',
            default: true
        }
    },
    type: 'object',
    required: ['indicator', 'start_date', 'end_date'],
    title: 'MacroDataRequest',
    description: 'Macro data request model'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PerformanceMetricsSchema = {
    properties: {
        total_return: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Return'
        },
        total_return_pct: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Return Pct'
        },
        sharpe_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharpe Ratio'
        },
        max_drawdown: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Drawdown'
        },
        total_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Trades'
        },
        winning_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Winning Trades'
        },
        losing_trades: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Losing Trades'
        },
        win_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Win Rate'
        },
        avg_win: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Win'
        },
        avg_loss: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Loss'
        },
        avg_annual_return: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Annual Return'
        },
        avg_annual_return_pct: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Annual Return Pct'
        },
        vwr: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vwr'
        },
        calmar_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Calmar Ratio'
        },
        sqn: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sqn'
        },
        avg_gross_leverage: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Gross Leverage'
        },
        max_gross_leverage: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Gross Leverage'
        },
        avg_positions_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Positions Value'
        },
        max_positions_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Positions Value'
        },
        final_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Value'
        },
        time_return: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Return'
        },
        time_drawdown: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Drawdown'
        },
        pyfolio_metrics: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pyfolio Metrics'
        }
    },
    type: 'object',
    title: 'PerformanceMetrics',
    description: 'Performance metrics model'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SignalCreateRequestSchema = {
    properties: {
        symbol: {
            type: 'string',
            title: 'Symbol',
            description: 'Trading symbol'
        },
        action: {
            type: 'string',
            title: 'Action',
            description: 'Signal action (buy/sell/hold)'
        },
        confidence: {
            type: 'number',
            title: 'Confidence',
            description: 'Signal confidence score (0-1)'
        },
        strategy_name: {
            type: 'string',
            title: 'Strategy Name',
            description: 'Strategy name'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata',
            description: 'Additional signal metadata'
        }
    },
    type: 'object',
    required: ['symbol', 'action', 'confidence', 'strategy_name'],
    title: 'SignalCreateRequest',
    description: 'Signal creation request model'
} as const;

export const SignalInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id',
            description: 'Signal ID'
        },
        symbol: {
            type: 'string',
            title: 'Symbol',
            description: 'Trading symbol'
        },
        action: {
            type: 'string',
            title: 'Action',
            description: 'Signal action (buy/sell/hold)'
        },
        confidence: {
            type: 'number',
            title: 'Confidence',
            description: 'Signal confidence score'
        },
        strategy_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Strategy Name',
            description: 'Strategy name'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp',
            description: 'Signal timestamp'
        },
        metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata',
            description: 'Additional signal metadata'
        }
    },
    type: 'object',
    required: ['id', 'symbol', 'action', 'confidence', 'timestamp', 'metadata'],
    title: 'SignalInfo',
    description: 'Signal information response model'
} as const;

export const SignalListResponseSchema = {
    properties: {
        signal: {
            items: {
                '$ref': '#/components/schemas/SignalInfo'
            },
            type: 'array',
            title: 'Signal',
            description: 'List of signals'
        },
        total: {
            type: 'integer',
            title: 'Total',
            description: 'Total number of signals'
        },
        page: {
            type: 'integer',
            title: 'Page',
            description: 'Current page number'
        },
        size: {
            type: 'integer',
            title: 'Size',
            description: 'Page size'
        }
    },
    type: 'object',
    required: ['signal', 'total', 'page', 'size'],
    title: 'SignalListResponse',
    description: 'Signal list response model'
} as const;

export const StockDataRequestSchema = {
    properties: {
        data_type: {
            type: 'string',
            title: 'Data Type',
            description: 'Data type: daily, minute, financial'
        },
        symbol: {
            type: 'string',
            title: 'Symbol',
            description: 'Stock symbol (e.g., 000001.SZ)'
        },
        start_date: {
            type: 'string',
            title: 'Start Date',
            description: 'Start date (e.g., 2022-01-01)'
        },
        end_date: {
            type: 'string',
            title: 'End Date',
            description: 'End date (e.g., 2022-12-31)'
        },
        use_cache: {
            type: 'boolean',
            title: 'Use Cache',
            description: 'Use cached data if available',
            default: true
        },
        freq: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Freq',
            description: "Frequency for minute data (e.g., 1min, 5min, 15min, 30min, 60min). Only required when data_type='minute'"
        }
    },
    type: 'object',
    required: ['data_type', 'symbol', 'start_date', 'end_date'],
    title: 'StockDataRequest',
    description: 'Stock data request model (for daily, minute, financial)'
} as const;

export const StrategiesListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StrategyInfo'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'StrategiesList',
    description: 'List of strategies'
} as const;

export const StrategyInfoSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'StrategyInfo',
    description: 'Strategy information model'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;