// This file is auto-generated by @hey-api/openapi-ts

/**
 * Signal information response model
 */
export type app__api__routes__signals__SignalInfo = {
    /**
     * Signal ID
     */
    id: string;
    /**
     * Trading symbol
     */
    symbol: string;
    /**
     * Signal action (buy/sell/hold)
     */
    action: string;
    /**
     * Signal confidence score
     */
    confidence: number;
    /**
     * Strategy name
     */
    strategy_name?: (string | null);
    /**
     * Signal timestamp
     */
    timestamp: string;
    /**
     * Additional signal metadata
     */
    metadata: {
        [key: string]: unknown;
    };
};

/**
 * Signal list response model
 */
export type app__api__routes__signals__SignalListResponse = {
    /**
     * List of signals
     */
    signal: Array<app__api__routes__signals__SignalInfo>;
    /**
     * Total number of signals
     */
    total: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Page size
     */
    size: number;
};

/**
 * Signal information response model
 */
export type app__api__routes__strategies__SignalInfo = {
    /**
     * Signal ID
     */
    id: string;
    /**
     * Signal generation time (ISO 8601)
     */
    signal_time: string;
    /**
     * Trading symbol
     */
    symbol: string;
    /**
     * Signal type (buy/sell/hold)
     */
    status: string;
    /**
     * Signal confidence (0-1)
     */
    signal_strength: number;
    /**
     * Signal price
     */
    price?: (number | null);
    /**
     * Suggested quantity
     */
    quantity?: (number | null);
    /**
     * Signal message
     */
    message?: (string | null);
};

/**
 * Signal list response model
 */
export type app__api__routes__strategies__SignalListResponse = {
    /**
     * List of signals
     */
    data: Array<app__api__routes__strategies__SignalInfo>;
    /**
     * Total number of signals
     */
    total: number;
};

/**
 * Backtest comparison response model
 */
export type BacktestComparison = {
    /**
     * Comparison ID
     */
    comparison_id: string;
    /**
     * Compared backtests
     */
    backtests: Array<BacktestComparisonItem>;
    /**
     * Comparison summary
     */
    summary: {
        [key: string]: unknown;
    };
    /**
     * Comparison timestamp
     */
    created_at: string;
};

/**
 * Backtest comparison item model
 */
export type BacktestComparisonItem = {
    /**
     * Backtest ID
     */
    backtest_id: string;
    /**
     * Strategy name
     */
    strategy_name: string;
    /**
     * Trading symbol
     */
    symbol: string;
    /**
     * Start date
     */
    start_date: string;
    /**
     * End date
     */
    end_date: string;
    /**
     * Initial capital
     */
    initial_capital: number;
    /**
     * Final portfolio value
     */
    final_value: number;
    /**
     * Total return
     */
    total_return: number;
    /**
     * Total return percentage
     */
    total_return_pct: number;
    /**
     * Sharpe ratio
     */
    sharpe_ratio?: (number | null);
    /**
     * Maximum drawdown
     */
    max_drawdown?: (number | null);
    /**
     * Total number of trades
     */
    total_trades?: (number | null);
    /**
     * Number of winning trades
     */
    winning_trades?: (number | null);
    /**
     * Number of losing trades
     */
    losing_trades?: (number | null);
    /**
     * Win rate
     */
    win_rate?: (number | null);
    /**
     * Average winning trade
     */
    avg_win?: (number | null);
    /**
     * Average losing trade
     */
    avg_loss?: (number | null);
    /**
     * Average annual return
     */
    avg_annual_return?: (number | null);
    /**
     * Variability-weighted return
     */
    vwr?: (number | null);
    /**
     * Calmar ratio
     */
    calmar_ratio?: (number | null);
    /**
     * System quality number
     */
    sqn?: (number | null);
    /**
     * Creation timestamp
     */
    created_at: string;
};

/**
 * Backtest history item model
 */
export type BacktestHistoryItem = {
    backtest_id: string;
    strategy_name: string;
    symbol: string;
    start_date: string;
    end_date: string;
    initial_capital: number;
    final_value: number;
    total_return: number;
    sharpe_ratio: number;
    max_drawdown: number;
    total_trades: number;
    win_rate: number;
    created_at: string;
};

/**
 * List of backtest history
 */
export type BacktestHistoryList = {
    data: Array<BacktestHistoryItem>;
    count: number;
    page: number;
    size: number;
    total_pages: number;
};

/**
 * Backtest request model
 */
export type BacktestRequest = {
    /**
     * Stock symbol (e.g., 000001.SZ)
     */
    symbol: string;
    /**
     * Start date (YYYY-MM-DD)
     */
    start_date: string;
    /**
     * End date (YYYY-MM-DD)
     */
    end_date: string;
    /**
     * Initial capital
     */
    initial_capital?: number;
    /**
     * Commission rate
     */
    commission?: number;
    /**
     * Commission type: PERC or FIXED
     */
    commtype?: string;
    /**
     * Minimum commission
     */
    commmin?: number;
    /**
     * Stock-like instrument
     */
    stocklike?: boolean;
    /**
     * Leverage ratio
     */
    leverage?: number;
    /**
     * Margin requirement
     */
    margin?: (number | null);
    /**
     * Trading mode
     */
    mode?: (string | null);
};

/**
 * Backtest response model
 */
export type BacktestResponse = {
    backtest_id: string;
    strategy_name: string;
    symbol: string;
    start_date: string;
    end_date: string;
    initial_capital: number;
    performance: PerformanceMetrics;
    chart_path?: (string | null);
    status: string;
};

/**
 * Backtest sorting options
 */
export type BacktestSortBy = 'created_at' | 'start_date' | 'end_date' | 'total_return' | 'sharpe_ratio' | 'max_drawdown' | 'total_trades';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * DataGroup configuration information
 */
export type DataGroupInfo = {
    /**
     * DataGroup name
     */
    name: string;
    /**
     * DataGroup class name (e.g., DailyDataGroup)
     */
    datagroup_class: string;
    /**
     * Data type (e.g., daily, minute)
     */
    data_type: string;
    /**
     * DataGroup weight in strategy
     */
    weight: number;
    /**
     * Factor instances in this group
     */
    factors: Array<FactorInstanceInfo>;
};

/**
 * Data response model
 */
export type DataResponse = {
    data: Array<{
        [key: string]: unknown;
    }>;
    count: number;
    columns: Array<(string)>;
};

/**
 * Factor calculation request model
 */
export type FactorCalculateRequest = {
    /**
     * Name of the factor to calculate
     */
    factor_name: string;
    /**
     * Type of data: daily, minute, financial, macro, industry, concept
     */
    data_type: string;
    /**
     * Symbol for stock/fundamental data
     */
    symbol?: (string | null);
    /**
     * Indicator for macro data
     */
    indicator?: (string | null);
    /**
     * Start date in YYYY-MM-DD format
     */
    start_date: string;
    /**
     * End date in YYYY-MM-DD format
     */
    end_date: string;
    /**
     * Additional parameters for factor calculation
     */
    parameters?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Factor calculation response model
 */
export type FactorCalculationResponse = {
    /**
     * Factor name
     */
    factor_name: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Calculation timestamp
     */
    calculation_time: string;
    /**
     * Number of data points calculated
     */
    data_points: number;
    /**
     * Calculation results
     */
    result_data: {
        [key: string]: unknown;
    };
};

/**
 * Factor information response model
 */
export type FactorInfo = {
    /**
     * Factor name
     */
    name: string;
    /**
     * Factor type
     */
    factor_type: string;
    /**
     * Factor class name
     */
    factor_class: string;
    /**
     * Factor description
     */
    description: string;
    /**
     * Factor parameters
     */
    parameters: {
        [key: string]: unknown;
    };
    /**
     * Required data fields
     */
    required_fields: Array<(string)>;
    /**
     * Factor status
     */
    status: string;
};

/**
 * Factor instance information in DataGroup
 */
export type FactorInstanceInfo = {
    /**
     * Factor instance name (e.g., MA_5_SMA)
     */
    instance_name: string;
    /**
     * Factor class name (e.g., MovingAverageFactor)
     */
    factor_class: string;
    /**
     * Factor instance parameters
     */
    parameters: {
        [key: string]: unknown;
    };
};

/**
 * Factor registration request model
 */
export type FactorRegisterRequest = {
    /**
     * Factor name
     */
    name: string;
    /**
     * Factor class name (e.g., MovingAverageFactor)
     */
    factor_class: string;
    /**
     * Factor description
     */
    description: string;
    /**
     * Factor parameters
     */
    parameters: {
        [key: string]: unknown;
    };
};

/**
 * Factor status response model
 */
export type FactorStatusResponse = {
    /**
     * Factor name
     */
    name: string;
    /**
     * Current status
     */
    status: string;
    /**
     * Last calculation time
     */
    last_calculation?: (string | null);
    /**
     * Number of errors
     */
    error_count: number;
    /**
     * Whether factor is available
     */
    is_available: boolean;
};

/**
 * Global backtest item model
 */
export type GlobalBacktestItem = {
    /**
     * Backtest ID
     */
    backtest_id: string;
    /**
     * Strategy name
     */
    strategy_name: string;
    /**
     * Trading symbol
     */
    symbol: string;
    /**
     * Start date
     */
    start_date: string;
    /**
     * End date
     */
    end_date: string;
    /**
     * Initial capital
     */
    initial_capital: number;
    /**
     * Final portfolio value
     */
    final_value?: (number | null);
    /**
     * Total return
     */
    total_return?: (number | null);
    /**
     * Total return percentage
     */
    total_return_pct?: (number | null);
    /**
     * Sharpe ratio
     */
    sharpe_ratio?: (number | null);
    /**
     * Maximum drawdown
     */
    max_drawdown?: (number | null);
    /**
     * Total number of trades
     */
    total_trades?: (number | null);
    /**
     * Number of winning trades
     */
    winning_trades?: (number | null);
    /**
     * Number of losing trades
     */
    losing_trades?: (number | null);
    /**
     * Win rate
     */
    win_rate?: (number | null);
    /**
     * Average winning trade
     */
    avg_win?: (number | null);
    /**
     * Average losing trade
     */
    avg_loss?: (number | null);
    /**
     * Average annual return
     */
    avg_annual_return?: (number | null);
    /**
     * Variability-weighted return
     */
    vwr?: (number | null);
    /**
     * Calmar ratio
     */
    calmar_ratio?: (number | null);
    /**
     * System quality number
     */
    sqn?: (number | null);
    /**
     * Backtest status
     */
    status: string;
    /**
     * Creation timestamp
     */
    created_at: string;
    /**
     * Creator email
     */
    created_by?: (string | null);
};

/**
 * Global backtest list response model
 */
export type GlobalBacktestList = {
    /**
     * List of backtests
     */
    data: Array<GlobalBacktestItem>;
    /**
     * Total number of backtests
     */
    count: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Page size
     */
    size: number;
    /**
     * Total number of pages
     */
    total_pages: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Industry/Concept data request model
 */
export type IndustryConceptDataRequest = {
    /**
     * Data type: industry, concept
     */
    data_type: string;
    /**
     * Use cached data if available
     */
    use_cache?: boolean;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Macro data request model
 */
export type MacroDataRequest = {
    /**
     * Data type: macro
     */
    data_type?: string;
    /**
     * Macro indicator: gdp, cpi, ppi, m2, interest_rate
     */
    indicator: string;
    /**
     * Start date (e.g., 2022-01-01)
     */
    start_date: string;
    /**
     * End date (e.g., 2022-12-31)
     */
    end_date: string;
    /**
     * Use cached data if available
     */
    use_cache?: boolean;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Performance metrics model
 */
export type PerformanceMetrics = {
    total_return?: (number | null);
    total_return_pct?: (number | null);
    sharpe_ratio?: (number | null);
    max_drawdown?: (number | null);
    total_trades?: (number | null);
    winning_trades?: (number | null);
    losing_trades?: (number | null);
    win_rate?: (number | null);
    avg_win?: (number | null);
    avg_loss?: (number | null);
    avg_annual_return?: (number | null);
    avg_annual_return_pct?: (number | null);
    vwr?: (number | null);
    calmar_ratio?: (number | null);
    sqn?: (number | null);
    avg_gross_leverage?: (number | null);
    max_gross_leverage?: (number | null);
    avg_positions_value?: (number | null);
    max_positions_value?: (number | null);
    final_value?: (number | null);
    time_return?: ({
    [key: string]: unknown;
} | null);
    time_drawdown?: ({
    [key: string]: unknown;
} | null);
    pyfolio_metrics?: ({
    [key: string]: unknown;
} | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Signal creation request model
 */
export type SignalCreateRequest = {
    /**
     * Trading symbol
     */
    symbol: string;
    /**
     * Signal action (buy/sell/hold)
     */
    action: string;
    /**
     * Signal confidence score (0-1)
     */
    confidence: number;
    /**
     * Strategy name
     */
    strategy_name: string;
    /**
     * Additional signal metadata
     */
    metadata?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Stock data request model (for daily, minute, financial)
 */
export type StockDataRequest = {
    /**
     * Data type: daily, minute, financial
     */
    data_type: string;
    /**
     * Stock symbol (e.g., 000001.SZ)
     */
    symbol: string;
    /**
     * Start date (e.g., 2022-01-01)
     */
    start_date: string;
    /**
     * End date (e.g., 2022-12-31)
     */
    end_date: string;
    /**
     * Use cached data if available
     */
    use_cache?: boolean;
    /**
     * Frequency for minute data (e.g., 1min, 5min, 15min, 30min, 60min). Only required when data_type='minute'
     */
    freq?: (string | null);
};

/**
 * List of strategies
 */
export type StrategiesList = {
    data: Array<StrategyInfo>;
    count: number;
};

/**
 * Detailed strategy information including DataGroup configs
 */
export type StrategyDetailInfo = {
    /**
     * Strategy name
     */
    name: string;
    /**
     * Strategy description
     */
    description?: (string | null);
    /**
     * DataGroup configurations
     */
    data_groups: Array<DataGroupInfo>;
};

/**
 * Strategy information model
 */
export type StrategyInfo = {
    name: string;
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type BacktestsListAllBacktestsData = {
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    size?: number;
    /**
     * Sort by field
     */
    sortBy?: BacktestSortBy;
    /**
     * Sort descending
     */
    sortDesc?: boolean;
    /**
     * Filter by start date from
     */
    startDateFrom?: (string | null);
    /**
     * Filter by start date to
     */
    startDateTo?: (string | null);
    /**
     * Filter by status
     */
    status?: (string | null);
    /**
     * Filter by strategy name
     */
    strategyName?: (string | null);
    /**
     * Filter by symbol
     */
    symbol?: (string | null);
};

export type BacktestsListAllBacktestsResponse = (GlobalBacktestList);

export type BacktestsCompareBacktestsData = {
    requestBody: Array<(string)>;
};

export type BacktestsCompareBacktestsResponse = (BacktestComparison);

export type BacktestsGetBacktestByIdData = {
    backtestId: string;
};

export type BacktestsGetBacktestByIdResponse = (GlobalBacktestItem);

export type DataFetchStockDataData = {
    requestBody: StockDataRequest;
};

export type DataFetchStockDataResponse = (DataResponse);

export type DataFetchMacroDataData = {
    requestBody: MacroDataRequest;
};

export type DataFetchMacroDataResponse = (DataResponse);

export type DataFetchIndustryConceptDataData = {
    requestBody: IndustryConceptDataRequest;
};

export type DataFetchIndustryConceptDataResponse = (DataResponse);

export type FactorsListFactorClassesResponse = (Array<{
    [key: string]: unknown;
}>);

export type FactorsListFactorsData = {
    factorType?: (string | null);
};

export type FactorsListFactorsResponse = (Array<FactorInfo>);

export type FactorsGetFactorData = {
    factorName: string;
};

export type FactorsGetFactorResponse = (FactorInfo);

export type FactorsUnregisterFactorData = {
    factorName: string;
};

export type FactorsUnregisterFactorResponse = (void);

export type FactorsCalculateFactorData = {
    requestBody: FactorCalculateRequest;
};

export type FactorsCalculateFactorResponse = (FactorCalculationResponse);

export type FactorsGetFactorStatusData = {
    factorName: string;
};

export type FactorsGetFactorStatusResponse = (FactorStatusResponse);

export type FactorsRegisterFactorData = {
    requestBody: FactorRegisterRequest;
};

export type FactorsRegisterFactorResponse = (FactorInfo);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SignalsListSignalsData = {
    page?: number;
    size?: number;
    symbol?: (string | null);
};

export type SignalsListSignalsResponse = (app__api__routes__signals__SignalListResponse);

export type SignalsCreateSignalData = {
    requestBody: SignalCreateRequest;
};

export type SignalsCreateSignalResponse = (app__api__routes__signals__SignalInfo);

export type SignalsGetSignalData = {
    signalId: string;
};

export type SignalsGetSignalResponse = (app__api__routes__signals__SignalInfo);

export type StrategiesListStrategiesResponse = (StrategiesList);

export type StrategiesGetStrategyData = {
    strategyName: string;
};

export type StrategiesGetStrategyResponse = (StrategyInfo);

export type StrategiesGetStrategyDetailData = {
    strategyName: string;
};

export type StrategiesGetStrategyDetailResponse = (StrategyDetailInfo);

export type StrategiesRunBacktestData = {
    requestBody: BacktestRequest;
    strategyName: string;
};

export type StrategiesRunBacktestResponse = (BacktestResponse);

export type StrategiesGetBacktestResultData = {
    backtestId: string;
    strategyName: string;
};

export type StrategiesGetBacktestResultResponse = (BacktestResponse);

export type StrategiesDeleteBacktestResultData = {
    backtestId: string;
    strategyName: string;
};

export type StrategiesDeleteBacktestResultResponse = (unknown);

export type StrategiesGetBacktestHistoryData = {
    page?: number;
    size?: number;
    strategyName: string;
};

export type StrategiesGetBacktestHistoryResponse = (BacktestHistoryList);

export type StrategiesGetBacktestSignalsData = {
    backtestId: string;
    strategyName: string;
};

export type StrategiesGetBacktestSignalsResponse = (app__api__routes__strategies__SignalListResponse);

export type StrategiesGetBacktestPriceDataData = {
    backtestId: string;
    strategyName: string;
};

export type StrategiesGetBacktestPriceDataResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);