"""add_push_fields_to_signal_model

Revision ID: 568589575e25
Revises: b81c3e8e3727
Create Date: 2025-10-29 22:39:45.733158

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '568589575e25'
down_revision = 'b81c3e8e3727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('push_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('signals', sa.Column('push_channels', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('signals', sa.Column('push_time', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('push_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.create_index(op.f('ix_signals_push_status'), 'signals', ['push_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_push_status'), table_name='signals')
    op.drop_column('signals', 'push_error')
    op.drop_column('signals', 'push_time')
    op.drop_column('signals', 'push_channels')
    op.drop_column('signals', 'push_status')
    # ### end Alembic commands ###
