"""Add signal_time and backtest_id to Signal model

Revision ID: 64101a0f09c9
Revises: a69a488eb7bf
Create Date: 2025-12-05 06:29:29.086271

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '64101a0f09c9'
down_revision = 'a69a488eb7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('signal_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('signals', sa.Column('backtest_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_signals_backtest_id'), 'signals', ['backtest_id'], unique=False)
    op.create_foreign_key(None, 'signals', 'backtest_result', ['backtest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_index(op.f('ix_signals_backtest_id'), table_name='signals')
    op.drop_column('signals', 'backtest_id')
    op.drop_column('signals', 'signal_time')
    # ### end Alembic commands ###
