"""Add data_type field to BacktestResult

Revision ID: b0b38e1cd1df
Revises: 8284820d4ca3
Create Date: 2025-12-08 02:48:31.383189

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "b0b38e1cd1df"
down_revision = "8284820d4ca3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column(
        "backtest_result",
        sa.Column(
            "data_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
    )

    # Step 2: Update existing rows with default value
    op.execute("UPDATE backtest_result SET data_type = 'daily' WHERE data_type IS NULL")

    # Step 3: Make column NOT NULL
    op.alter_column("backtest_result", "data_type", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_result", "data_type")
    # ### end Alembic commands ###
