"""Remove signal_type and add strategy_name to Signal model

Revision ID: d648e77d566d
Revises: 568589575e25
Create Date: 2025-11-26 22:51:48.454796

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd648e77d566d'
down_revision = '568589575e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('strategy_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.create_index(op.f('ix_signals_strategy_name'), 'signals', ['strategy_name'], unique=False)
    op.drop_constraint(op.f('signals_strategy_id_fkey'), 'signals', type_='foreignkey')
    op.drop_column('signals', 'signal_type')
    op.drop_column('signals', 'strategy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('strategy_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('signals', sa.Column('signal_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('signals_strategy_id_fkey'), 'signals', 'strategies', ['strategy_id'], ['id'])
    op.drop_index(op.f('ix_signals_strategy_name'), table_name='signals')
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.drop_column('signals', 'strategy_name')
    # ### end Alembic commands ###
